//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMember
    {
        public long Emp_ID { get; set; }
        public string CoM_Title { get; set; }
        public string CoM_ImagePath { get; set; }
        public string CoM_OrganizationalStructure { get; set; }
        public Nullable<int> CoM_OSSortingOrder { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
