//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUs
    {
        public int CU_ID { get; set; }
        public string CU_Name { get; set; }
        public string CU_Mobile { get; set; }
        public string CU_Email { get; set; }
        public string CU_Message { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
