//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfiguration
    {
        public int SMTPServer_ID { get; set; }
        public string SMTPHost { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public string SignInName { get; set; }
        public string Password { get; set; }
        public string MailFrom { get; set; }
        public string DisplayName { get; set; }
        public bool SSLEnabled { get; set; }
    }
}
