//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeService
    {
        public long Emp_ID { get; set; }
        public System.DateTime EmS_OnDate { get; set; }
        public Nullable<int> EmS_TotalSalary { get; set; }
        public Nullable<int> EmS_EndOfServiceBenefit { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
