//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.CostingBreakdownDetails = new HashSet<CostingBreakdownDetail>();
            this.LoanAmounts = new HashSet<LoanAmount>();
            this.SubscriptionTransactions = new HashSet<SubscriptionTransaction>();
            this.TransactionCommitteeDecisions = new HashSet<TransactionCommitteeDecision>();
            this.EmployeeServices = new HashSet<EmployeeService>();
            this.FundSubscriptions = new HashSet<FundSubscription>();
            this.ExceptionAmounts = new HashSet<ExceptionAmount>();
            this.LoanExceptions = new HashSet<LoanException>();
            this.TransactionCommitteeDecisions1 = new HashSet<TransactionCommitteeDecision>();
            this.SubscriptionTransactions1 = new HashSet<SubscriptionTransaction>();
            this.SubscriptionTransactions2 = new HashSet<SubscriptionTransaction>();
            this.MeetingTransactions = new HashSet<MeetingTransaction>();
            this.HRSheetDatas = new HashSet<HRSheetData>();
        }
    
        public long Emp_ID { get; set; }
        public string Emp_Password { get; set; }
        public Nullable<int> Emp_Role { get; set; }
        public Nullable<bool> Emp_IsAdmin { get; set; }
        public Nullable<bool> Emp_IsHelpDesk { get; set; }
        public Nullable<bool> Emp_AccountStatus { get; set; }
        public string Emp_FullName { get; set; }
        public string Emp_Position { get; set; }
        public string Emp_Department { get; set; }
        public string Emp_Nationality { get; set; }
        public Nullable<System.DateTime> Emp_JoiningDate { get; set; }
        public Nullable<int> Emp_Gender { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_MobileNumber { get; set; }
        public Nullable<System.DateTime> Emp_DateOfBirth { get; set; }
        public string Emp_JobDegree { get; set; }
        public Nullable<bool> Emp_IsLocalCitizen { get; set; }
        public string Emp_Password_Enc { get; set; }
        public string SecurityStamp { get; set; }
    
        public virtual CommitteeMember CommitteeMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostingBreakdownDetail> CostingBreakdownDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanAmount> LoanAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionTransaction> SubscriptionTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionCommitteeDecision> TransactionCommitteeDecisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeService> EmployeeServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundSubscription> FundSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionAmount> ExceptionAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanException> LoanExceptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionCommitteeDecision> TransactionCommitteeDecisions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionTransaction> SubscriptionTransactions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionTransaction> SubscriptionTransactions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingTransaction> MeetingTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas { get; set; }
    }
}
