//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionAmount
    {
        public long Emp_ID { get; set; }
        public int Exc_PrimaryBalancer { get; set; }
        public Nullable<int> FSu_ID { get; set; }
        public Nullable<int> Exc_Amount { get; set; }
        public Nullable<bool> Exc_IsUsed { get; set; }
        public string Exc_Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FundSubscription FundSubscription { get; set; }
    }
}
