//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRSheet()
        {
            this.HRSheetDatas = new HashSet<HRSheetData>();
            this.HRSheetDatas1 = new HashSet<HRSheetData>();
            this.HRSheetDatas2 = new HashSet<HRSheetData>();
            this.HRSheetDatas3 = new HashSet<HRSheetData>();
            this.HRSheetDatas4 = new HashSet<HRSheetData>();
            this.HRSheetDatas5 = new HashSet<HRSheetData>();
            this.HRSheetDatas6 = new HashSet<HRSheetData>();
            this.HRSheetDatas7 = new HashSet<HRSheetData>();
            this.HRSheetData_New = new HashSet<HRSheetData_New>();
        }
    
        public int HRS_ID { get; set; }
        public int HRS_Serial { get; set; }
        public System.DateTime HRS_Date { get; set; }
        public string HRS_Notes { get; set; }
        public Nullable<bool> HRS_IsClosedNormalSheet { get; set; }
        public Nullable<bool> HRS_IsClosedNewSubsSheet { get; set; }
        public Nullable<bool> HRS_IsClosedCancelledSubsSheet { get; set; }
        public Nullable<bool> HRS_IsClosedModificationSheet { get; set; }
        public Nullable<bool> HRS_IsClosedNewLoansSheet { get; set; }
        public Nullable<bool> HRS_IsClosedCancelledLoansSheet { get; set; }
        public bool HRS_IsSubsequentSheet { get; set; }
        public Nullable<bool> HRS_IsClosedInstallmentModificationSheet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData> HRSheetDatas7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData_New> HRSheetData_New { get; set; }
    }
}
