//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRSheetData
    {
        public long HRSD_ID { get; set; }
        public int HRS_ID { get; set; }
        public long Emp_ID { get; set; }
        public string HRSD_FullName { get; set; }
        public string HRSD_Department { get; set; }
        public string HRSD_Position { get; set; }
        public Nullable<System.DateTime> HRSD_JoiningDate { get; set; }
        public Nullable<int> HRSD_Salary { get; set; }
        public Nullable<int> HRSD_SubsAmount { get; set; }
        public Nullable<int> HRSD_FundAmount { get; set; }
        public Nullable<int> HRSD_LoanAmount { get; set; }
        public Nullable<int> HRSD_LoanInstallment { get; set; }
        public Nullable<int> HRSD_LoanPaidAmount { get; set; }
        public Nullable<int> HRSD_LoanRemainingAmount { get; set; }
        public bool HRSD_IsNewSubscription { get; set; }
        public bool HRSD_IsModifiedSubscription { get; set; }
        public bool HRSD_IsCancelledSubscription { get; set; }
        public bool HRSD_IsNewLoan { get; set; }
        public bool HRSD_IsModifiedLoan { get; set; }
        public bool HRSD_IsCancelledLoan { get; set; }
        public bool HRSD_IsIncludedInNormalSheet { get; set; }
        public bool HRSD_IsIncludedInNewSubsSheet { get; set; }
        public bool HRSD_IsIncludedInCancelledSubsSheet { get; set; }
        public bool HRSD_IsIncludedInModificationSheet { get; set; }
        public bool HRSD_IsIncludedInNewLoansSheet { get; set; }
        public bool HRSD_IsIncludedInCancelledLoansSheet { get; set; }
        public Nullable<int> HRSD_NewSheetID_NS { get; set; }
        public Nullable<int> HRSD_NewSheetID_MS { get; set; }
        public Nullable<int> HRSD_NewSheetID_CS { get; set; }
        public Nullable<int> HRSD_NewSheetID_NL { get; set; }
        public Nullable<int> HRSD_NewSheetID_ML { get; set; }
        public Nullable<int> HRSD_NewSheetID_CL { get; set; }
        public Nullable<int> HRSD_NewSheetID_Normal { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual HRSheet HRSheet { get; set; }
        public virtual HRSheet HRSheet1 { get; set; }
        public virtual HRSheet HRSheet2 { get; set; }
        public virtual HRSheet HRSheet3 { get; set; }
        public virtual HRSheet HRSheet4 { get; set; }
        public virtual HRSheet HRSheet5 { get; set; }
        public virtual HRSheet HRSheet6 { get; set; }
        public virtual HRSheet HRSheet7 { get; set; }
    }
}
