//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanException
    {
        public long Emp_ID { get; set; }
        public int FSu_ID { get; set; }
        public Nullable<int> LEx_MaxAmount { get; set; }
        public Nullable<bool> LEx_MaxAmount_IsUsed { get; set; }
        public Nullable<bool> LEx_LessSubscriptionPeriodForLoan { get; set; }
        public string LEx_Notes { get; set; }
        public Nullable<bool> LEx_CanRequestLoanWithCurrentActiveLoan { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FundSubscription FundSubscription { get; set; }
    }
}
