//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakafulEntities : DbContext
    {
        public TakafulEntities()
            : base("name=TakafulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovalStatu> ApprovalStatus { get; set; }
        public virtual DbSet<CommitteeMember> CommitteeMembers { get; set; }
        public virtual DbSet<CostingBreakdownDetail> CostingBreakdownDetails { get; set; }
        public virtual DbSet<EmailConfiguration> EmailConfigurations { get; set; }
        public virtual DbSet<FundSubscription> FundSubscriptions { get; set; }
        public virtual DbSet<LoanAmount> LoanAmounts { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<RoleControlPage> RoleControlPages { get; set; }
        public virtual DbSet<SolidarityFundInformation> SolidarityFundInformations { get; set; }
        public virtual DbSet<SubscriptionInformation> SubscriptionInformations { get; set; }
        public virtual DbSet<SubscriptionTransaction> SubscriptionTransactions { get; set; }
        public virtual DbSet<TransactionCommitteeDecision> TransactionCommitteeDecisions { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<SystemExceptionLog> SystemExceptionLog { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeService> EmployeeServices { get; set; }
        public virtual DbSet<ExceptionAmount> ExceptionAmounts { get; set; }
        public virtual DbSet<LoanException> LoanExceptions { get; set; }
        public virtual DbSet<HRSheet> HRSheets { get; set; }
        public virtual DbSet<MeetingTransaction> MeetingTransactions { get; set; }
        public virtual DbSet<HRSheetData> HRSheetDatas { get; set; }
        public virtual DbSet<HRSheetData_New> HRSheetData_New { get; set; }
        public virtual DbSet<SubscriptionRulesAcceptance> SubscriptionRulesAcceptances { get; set; }
    }
}
