//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingTransaction
    {
        public int Mee_ID { get; set; }
        public long Emp_ID { get; set; }
        public int SuT_Year { get; set; }
        public int SuT_Serial { get; set; }
        public int SuT_SubscriptionType { get; set; }
        public Nullable<System.DateTime> MeT_Date { get; set; }
        public Nullable<int> MeT_ApprovedAmount { get; set; }
        public Nullable<System.DateTime> MeT_ApprovedAmountDate { get; set; }
        public Nullable<long> MeT_ApprovedAmountAdminID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Meeting Meeting { get; set; }
        public virtual SubscriptionTransaction SubscriptionTransaction { get; set; }
    }
}
