//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolidarityFundInformation
    {
        public int SFI_ID { get; set; }
        public string SFI_GeneralEmail { get; set; }
        public string SFI_HomePageBannerPhrase_1 { get; set; }
        public string SFI_HomePageBannerFilePath_1 { get; set; }
        public string SFI_HomePageBannerPhrase_2 { get; set; }
        public string SFI_HomePageBannerFilePath_2 { get; set; }
        public string SFI_HomePageBannerPhrase_3 { get; set; }
        public string SFI_HomePageBannerFilePath_3 { get; set; }
        public string SFI_SFInfoFilePath1 { get; set; }
        public string SFI_SFInfoFilePath2 { get; set; }
        public string SFI_SFInfoFilePath3 { get; set; }
        public string SFI_SFInfoFilePath4 { get; set; }
    }
}
