//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionRulesAcceptance
    {
        public int ID { get; set; }
        public int Emp_ID { get; set; }
        public Nullable<System.DateTime> AcceptanceDate { get; set; }
        public Nullable<bool> Acceptance { get; set; }
        public string Source { get; set; }
    }
}
