//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionTransaction()
        {
            this.TransactionCommitteeDecisions = new HashSet<TransactionCommitteeDecision>();
            this.MeetingTransactions = new HashSet<MeetingTransaction>();
            this.HRSheetData_New = new HashSet<HRSheetData_New>();
        }
    
        public long Emp_ID { get; set; }
        public int SuT_Year { get; set; }
        public int SuT_Serial { get; set; }
        public int SuT_SubscriptionType { get; set; }
        public Nullable<System.DateTime> SuT_Date { get; set; }
        public Nullable<int> SuT_Amount { get; set; }
        public string SuT_Notes { get; set; }
        public Nullable<int> SuT_ApprovalStatus { get; set; }
        public Nullable<System.DateTime> SuT_ApprovalDate { get; set; }
        public string SuT_ApprovalNotes { get; set; }
        public Nullable<int> SuI_ID { get; set; }
        public int SortIndex { get; set; }
        public Nullable<long> SuT_ServiceEmployeeID { get; set; }
        public string SuT_NotesForCommittee { get; set; }
        public Nullable<int> FSu_ID { get; set; }
        public Nullable<int> LAm_ID { get; set; }
        public Nullable<long> SuT_AdminID { get; set; }
    
        public virtual ApprovalStatu ApprovalStatu { get; set; }
        public virtual SubscriptionInformation SubscriptionInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionCommitteeDecision> TransactionCommitteeDecisions { get; set; }
        public virtual FundSubscription FundSubscription { get; set; }
        public virtual LoanAmount LoanAmount { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingTransaction> MeetingTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRSheetData_New> HRSheetData_New { get; set; }
    }
}
