//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionInformation()
        {
            this.SubscriptionTransactions = new HashSet<SubscriptionTransaction>();
        }
    
        public int SuI_ID { get; set; }
        public Nullable<bool> SuI_IsActive { get; set; }
        public Nullable<int> SuI_MinimumSubscription { get; set; }
        public Nullable<int> SuI_MinimumAmount { get; set; }
        public Nullable<int> SuI_MaximumAmount { get; set; }
        public Nullable<int> SuI_NumberOfInstallments { get; set; }
        public Nullable<int> SuI_LessSubscriptionPeriodForLoan { get; set; }
        public Nullable<int> SuI_SubscriptionAmount { get; set; }
        public Nullable<int> SuI_LoanFirstAmount { get; set; }
        public Nullable<int> SuI_LoanMaximumAmount { get; set; }
        public Nullable<int> SuI_PeriodBetweenLoans { get; set; }
        public Nullable<int> SuI_MaxDeductionPercentage { get; set; }
        public Nullable<int> SuI_LessPeriodForReSbubscrition { get; set; }
        public Nullable<int> SuI_LessPeriodForLoan4ReSubscriber { get; set; }
        public Nullable<int> SuI_LessPeriodForLoanNewEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionTransaction> SubscriptionTransactions { get; set; }
    }
}
