//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakafulResponsiveApplication.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionCommitteeDecision
    {
        public long Emp_ID { get; set; }
        public int SuT_Year { get; set; }
        public int SuT_Serial { get; set; }
        public int SuT_SubscriptionType { get; set; }
        public long TCD_CommitteeMemberID { get; set; }
        public int TCD_CommitteeApprovalStatus { get; set; }
        public Nullable<System.DateTime> TCD_Date { get; set; }
        public Nullable<long> TCD_AdminID { get; set; }
    
        public virtual SubscriptionTransaction SubscriptionTransaction { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
